//! generated by zig-lsp-codegen

const tres = @import("tres");
const Undefinedable = tres.Undefinedable;

pub const Uri = []const u8;
pub const DocumentUri = []const u8;
pub const RegExp = []const u8;
