//! Metamodel schema
//! Autogenerated by JSON Schema -> Zig tooling

const tres = @import("tres");
const Undefinedable = tres.Undefinedable;

enumerations: []Enumeration,
notifications: []Notification,
requests: []Request,
structures: []Structure,
typeAliases: []TypeAlias,

pub const AndType = struct {
    comptime kind: []const u8 = "and",

    items: []Type,
};

pub const ArrayType = struct {
    comptime kind: []const u8 = "array",

    element: *Type,
};

pub const BaseType = struct {
    comptime kind: []const u8 = "base",

    name: BaseTypes,
};

pub const BaseTypes = enum {
    Uri,
    DocumentUri,
    integer,
    uinteger,
    decimal,
    RegExp,
    string,
    boolean,
    @"null",
};

pub const BooleanLiteralType = struct {
    comptime kind: []const u8 = "booleanLiteral",

    value: bool,
};

pub const Enumeration = struct {
    documentation: Undefinedable([]const u8),
    name: []const u8,
    proposed: Undefinedable(bool),
    since: Undefinedable([]const u8),
    supportsCustomValues: Undefinedable(bool),
    type: EnumerationType,
    values: []EnumerationEntry,
};

pub const EnumerationEntry = struct {
    documentation: Undefinedable([]const u8),
    name: []const u8,
    proposed: Undefinedable(bool),
    since: Undefinedable([]const u8),
    value: union(enum) {
        number: f64,
        string: []const u8,
    },
};

pub const EnumerationType = struct {
    comptime kind: []const u8 = "base",

    name: enum {
        string,
        integer,
    },
};

pub const IntegerLiteralType = struct {
    comptime kind: []const u8 = "integerLiteral",

    value: f64,
};

pub const MapKeyType = union(enum) {
    base: struct {
        comptime kind: []const u8 = "base",

        name: enum {
            Uri,
            DocumentUri,
            string,
            integer,
        },
    },
    ReferenceType: ReferenceType,
};

pub const MapType = struct {
    comptime kind: []const u8 = "map",

    key: MapKeyType,
    value: *Type,
};

pub const Notification = struct {
    documentation: Undefinedable([]const u8),
    method: []const u8,
    params: Undefinedable(union(enum) {
        Type: Type,
        array_of_Type: []Type,
    }),
    proposed: Undefinedable(bool),
    registrationOptions: Undefinedable(Type),
    since: Undefinedable([]const u8),
};

pub const OrType = struct {
    comptime kind: []const u8 = "or",

    items: []Type,
};

pub const Property = struct {
    documentation: Undefinedable([]const u8),
    name: []const u8,
    optional: Undefinedable(bool),
    proposed: Undefinedable(bool),
    since: Undefinedable([]const u8),
    type: Type,
};

pub const ReferenceType = struct {
    comptime kind: []const u8 = "reference",

    name: []const u8,
};

pub const Request = struct {
    documentation: Undefinedable([]const u8),
    errorData: Undefinedable(Type),
    method: []const u8,
    params: Undefinedable(union(enum) {
        Type: Type,
        array_of_Type: []Type,
    }),
    partialResult: Undefinedable(Type),
    proposed: Undefinedable(bool),
    registrationOptions: Undefinedable(Type),
    result: Type,
    since: Undefinedable([]const u8),
};

pub const StringLiteralType = struct {
    comptime kind: []const u8 = "stringLiteral",

    value: []const u8,
};

pub const Structure = struct {
    documentation: Undefinedable([]const u8),
    extends: Undefinedable([]Type),
    mixins: Undefinedable([]Type),
    name: []const u8,
    properties: []Property,
    proposed: Undefinedable(bool),
    since: Undefinedable([]const u8),
};

pub const StructureLiteral = struct {
    documentation: Undefinedable([]const u8),
    properties: []Property,
    proposed: Undefinedable(bool),
    since: Undefinedable([]const u8),
};

pub const StructureLiteralType = struct {
    comptime kind: []const u8 = "literal",

    value: StructureLiteral,
};

pub const TupleType = struct {
    comptime kind: []const u8 = "tuple",

    items: []Type,
};

pub const Type = union(enum) {
    BaseType: BaseType,
    ReferenceType: ReferenceType,
    ArrayType: ArrayType,
    MapType: MapType,
    AndType: AndType,
    OrType: OrType,
    TupleType: TupleType,
    StructureLiteralType: StructureLiteralType,
    StringLiteralType: StringLiteralType,
    IntegerLiteralType: IntegerLiteralType,
    BooleanLiteralType: BooleanLiteralType,
};

pub const TypeAlias = struct {
    documentation: Undefinedable([]const u8),
    name: []const u8,
    proposed: Undefinedable(bool),
    since: Undefinedable([]const u8),
    type: Type,
};

pub const TypeKind = enum {
    base,
    reference,
    array,
    map,
    @"and",
    @"or",
    tuple,
    literal,
    stringLiteral,
    integerLiteral,
    booleanLiteral,
};
